### PR TITLE
add a1_config

### PR DESCRIPTION
**Pull request by robotlearning123**

### CODE REVIEW

**Comment by grassjelly** [comment]
Hey thanks for the PR. Could you add the new robot in the README (supported robots and credits to the description package) plus the source of the robot description here: https://github.com/chvmp/robots/blob/master/install_descriptions

**Comment by robotlearning123** [comment]
Hi @grassjelly. Thank you for your review. Update the new robot in README. The A1 robot description is has same repo with Aliengo & Go1: https://github.com/chvmp/unitree_ros.

**Comment by juno100** [comment]
a1 robot does not work teleop.
What is the problem?

**Comment by robotlearning123** [comment]
Hi @juno100. Thank you for your review. I will test it when getting the joystick.

**Comment by juno100** [comment]
thank you for response!

a1 didn't work roslaunch a1_config bringup.launch rviz:=true

it can't get the urdf transform

**Comment by robotlearning123** [comment]
Thank you! I will do more tests.

**Comment by juno100** [comment]
thanks ...!!!

**Pull request merged**
